passwd:
  users:
    - name: whenke
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQ3M0ToiNWuS3tFPLaUjx4YM2AjnxABNl0DlpdKY6wFJK1XtT/2r/JoWXCx4t0VpVsfgpHPS+yVnW//p+KTq4BYgoXHvfowXc7zlkBl8cD/FHdKTA3C19rHg/6ReqopL1POBBlJ5kQQysSrK1OxeWTm/nzCThE5UDynS3UQV2/SlxRsg7P3B8oVbkwofg/Qf1aMq91tZNxBaFMKnTQcfb1ZOB1jrhpuc9//HzqgpO/lO6WcJA48lI7Do2Ga5SGgvOKRn+IhIbU1cp1iaZUgzcoqvb2QtbtsrLU2SRqKU90dyF26UnBxTYYmPfDjXvrTzAKyEvt2Z6LR63Mzp4RwfY0/qUXWD2yIxSVO/t3hu2TDGOHaJLpQd+i/5wzWz/VZcZWs6jHt+/+yesVFqZpEfjfV9jzzfny7lx3fHFCHu+3HUmBg62GGWQ5FU8QGWoeWJVP4TZeEvjnWi+/xjSBgQswAyg696ZlrbYEr6+UMyfO5ajjDs4d7nPUj3yDEGl/OoCBSrQCKr1UKhToaTE3HFSKOv/VMptmHp7p7Z7UF6KVy+sdFfCjXw1gdZByWW10zLpI8AUvaioeuM774Jm9tR0kCpUDo2F9jzl1l8dgTwwqlkfPA0hcNzeOVBkxn06/hOfQ2JBvYdg46CIUPC5DhV8EHfMmScq5dPyTlh+nrvzaqQ== whenke@cogolabs.com"
      home_dir: "/home/whenke"
      groups:
        - "sudo"
      shell: "/bin/bash"
update:
  group: "stable"
locksmith:
  reboot_strategy: "reboot"
  window_start: "05:00"
  window_length: "1h"
storage:
  files:
    - path: "/usr/local/bin/k3s"
      filesystem: "root"
      contents:
        remote:
          url: "https://github.com/rancher/k3s/releases/download/v0.4.0/k3s"
      mode: 777
systemd:
  units:
    - name: "k3s-agent.service"
      enabled: true
      contents: |
        [Unit]
        Description=Lightweight Kubernetes
        Documentation=https://k3s.io
        After=network.target

        [Service]
        Type=exec
        ExecStartPre=-/sbin/modprobe br_netfilter
        ExecStartPre=-/sbin/modprobe overlay
        ExecStart=/usr/local/bin/k3s agent --server https://192.168.1.30:6443 --token K103785d4aff7aeacf8100cdc44b815b21687cd84c7ad73725f2efce33d98ac9009::node:e4bc72a2b7f4b35b68d7ff2d826fc79b --no-flannel --kubelet-arg allow-privileged=true
        KillMode=process
        Delegate=yes
        LimitNOFILE=infinity
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        [Install]
        WantedBy=multi-user.target
