passwd:
  users:
    - name: "core"
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQ3M0ToiNWuS3tFPLaUjx4YM2AjnxABNl0DlpdKY6wFJK1XtT/2r/JoWXCx4t0VpVsfgpHPS+yVnW//p+KTq4BYgoXHvfowXc7zlkBl8cD/FHdKTA3C19rHg/6ReqopL1POBBlJ5kQQysSrK1OxeWTm/nzCThE5UDynS3UQV2/SlxRsg7P3B8oVbkwofg/Qf1aMq91tZNxBaFMKnTQcfb1ZOB1jrhpuc9//HzqgpO/lO6WcJA48lI7Do2Ga5SGgvOKRn+IhIbU1cp1iaZUgzcoqvb2QtbtsrLU2SRqKU90dyF26UnBxTYYmPfDjXvrTzAKyEvt2Z6LR63Mzp4RwfY0/qUXWD2yIxSVO/t3hu2TDGOHaJLpQd+i/5wzWz/VZcZWs6jHt+/+yesVFqZpEfjfV9jzzfny7lx3fHFCHu+3HUmBg62GGWQ5FU8QGWoeWJVP4TZeEvjnWi+/xjSBgQswAyg696ZlrbYEr6+UMyfO5ajjDs4d7nPUj3yDEGl/OoCBSrQCKr1UKhToaTE3HFSKOv/VMptmHp7p7Z7UF6KVy+sdFfCjXw1gdZByWW10zLpI8AUvaioeuM774Jm9tR0kCpUDo2F9jzl1l8dgTwwqlkfPA0hcNzeOVBkxn06/hOfQ2JBvYdg46CIUPC5DhV8EHfMmScq5dPyTlh+nrvzaqQ=="
      shell: "/bin/bash"
update:
  group: "stable"
locksmith:
  reboot_strategy: "reboot"
  window_start: "05:00"
  window_length: "1h"
storage:
  files:
    - path: "/opt/k3s"
      filesystem: "root"
      contents:
        remote:
          url: "https://github.com/rancher/k3s/releases/download/v0.4.0/k3s"
      mode: 777
    - path: "/etc/hostname"
      filesystem: "root"
      mode: 420
      contents:
        inline: "coreos"
    - path: "/etc/cni/net.d/10-flannel.conflist"
      filesystem: "root"
      mode: 644
      contents:
        inline: |
          {
            "name": "cbr0",
            "plugins": [
              {
                "type": "flannel",
                "delegate": {
                  "hairpinMode": true,
                  "isDefaultGateway": true
                }
              },
              {
                "type": "portmap",
                "capabilities": {
                  "portMappings": true
                }
              }
            ]
          }
    - path: "/opt/cni/bin/loopback"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/loopback"
    - path: "/opt/cni/bin/bridge"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/bridge"
    - path: "/opt/cni/bin/flannel"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/flannel"
    - path: "/opt/cni/bin/host-device"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/host-device"
    - path: "/opt/cni/bin/host-local"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/host-local"
    - path: "/opt/cni/bin/dhcp"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/dhcp"
    - path: "/opt/cni/bin/ipvlan"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/ipvlan"
    - path: "/opt/cni/bin/macvlan"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/macvlan"
    - path: "/opt/cni/bin/portmap"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/portmap"
    - path: "/opt/cni/bin/ptp"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/ptp"
    - path: "/opt/cni/bin/tuning"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/tuning"
    - path: "/opt/cni/bin/vlan"
      filesystem: "root"
      mode: 755
      contents:
        remote:
          url: "https://github.com/Dev-Time/container-linux-config/raw/master/cni-plugins-amd64-v0.7.5/vlan"
systemd:
  units:
    - name: "k3s-agent.service"
      enabled: true
      contents: |
        [Unit]
        Description=Lightweight Kubernetes
        Documentation=https://k3s.io
        After=network.target

        [Service]
        Type=exec
        ExecStartPre=-/sbin/modprobe br_netfilter
        ExecStartPre=-/sbin/modprobe overlay
        ExecStart=/opt/k3s agent --server https://192.168.1.30:6443 --token K105890d06857be9ddcd1bd4fc31488c1bf9abfc02c956af9bb481497c6c28a5579::node:8b0104de554cfa3909b16fa6ff89cffb --no-flannel --kubelet-arg allow-privileged=true
        KillMode=process
        Delegate=yes
        LimitNOFILE=infinity
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        [Install]
        WantedBy=multi-user.target
